config/routes.rb
Sneakerlife::Application.routes.draw do
  resources :countdowns
  resources :devise
  resources :registrations
  resources :checkout
  resources :sell_shoes
  resources :buy_shoes

  resources :posts

   devise_for :users

  root :to => 'posts#index'

end

app/controllers/sell_shoes_controller.rb
class SellShoesController < ApplicationController
  # GET /shoes
  # GET /shoes.json
  
  before_filter :authenticate_user!

  def authorize_admin
    unless current_user.try :admin? then
      redirect_to root_path
    end
  end
  
  def index
    @shoes = Shoe.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shoes }
    end
  end

  # GET /shoes/1
  # GET /shoes/1.json
  def show
    @shoe = Shoe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shoe }
    end
  end

  # GET /shoes/new
  # GET /shoes/new.json
  def new
    @shoe = Shoe.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shoe }
    end
  end

  # GET /shoes/1/edit
  def edit
    @shoe = Shoe.find(params[:id])
  end

  # POST /shoes
  # POST /shoes.json
  def create
    params[:price] = params[:price].to_f
    @shoe = Shoe.new(params[:shoe])

    respond_to do |format|
      if @shoe.save
        format.html { redirect_to @shoe, notice: 'Shoe was successfully created.' }
        format.json { render json: @shoe, status: :created, location: @shoe }
      else
        format.html { render action: "new" }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shoes/1
  # PUT /shoes/1.json
  def update
    params[:shoe][:price] = params[:shoe][:price].to_f
    @shoe = Shoe.find(params[:id])

    respond_to do |format|
      if @shoe.update_attributes(params[:shoe])
        format.html { redirect_to @shoe, notice: 'Shoe was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shoes/1
  # DELETE /shoes/1.json
  def destroy
    @shoe = Shoe.find(params[:id])
    @shoe.destroy

    respond_to do |format|
      format.html { redirect_to shoes_url }
      format.json { head :ok }
    end
  end
end

app/views/sell_shoes/_form.html.haml
= form_for(@shoe,:url => sell_shoes_path, :html => {:multipart => true}) do |f|
  -if @shoe.errors.any?
    #error_explanation
      %h2= "#{pluralize(@shoe.errors.count, "error")} prohibited this shoe from being saved:"
      %ul
        - @shoe.errors.full_messages.each do |msg|
          %li= msg
          
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :brand
    = f.text_field :brand
  .field
    = f.label :size
    = f.text_field :size
  .field
    = f.label :price
    = f.text_field :price
  .field
    = f.label :condition
    = f.text_field :condition
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.file_field :image
    
  .actions
    %div
    = f.submit 'submit'

app/views/sell_shoes/edit.html.haml
%h1 Editing Your Listing

= render 'form'

= link_to 'view details', sell_shoe_path
\|
= link_to 'Back', sell_shoes_path

app/views/sell_shoes/index.html.haml
%h1 Exotic Sneakers For Sale

%table
  %tr
    %th
    %th
    %th

  - @shoes.each do |shoe|
    %tr
      %td= shoe.name
      %td= shoe.brand
      %td= shoe.size
      %td= shoe.condition
      %td= number_to_currency shoe.price
      %td= image_tag shoe.image.url(:medium)
      %td= link_to 'View Details', sell_shoe_path(shoe)
      %td= link_to 'Edit', edit_sell_shoe_path(shoe)
      %td= link_to 'Delete From Market', sell_shoe_path(shoe), :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'Sell More Exotic Sneakers', new_sell_shoe_path

app/views/sell_shoes/new.html.haml
%h1 Sell Your Exoctics!
%h2 Please fill out all information below

//%form_for :sell_shoe_path(shoe), :html => {:multipart => true} do |form|
//%form.file_field :shoe_images


// render :partial => 'form', :locals => {:sell_shoe_path => @shoe}sell_shoe_path(shoe)

= render 'form'
= link_to 'Back', sell_shoes_path

app/views/sell_shoes/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_sell_shoe_path(@shoe)
\|
= link_to 'Back', sell_shoes_path

= number_to_currency @shoe.price
= image_tag @shoe.image.url
= image_tag @shoe.image.url(:medium)
= image_tag @shoe.image.url(:thumb)