config/routes.rb
Sneakerlife::Application.routes.draw do
  resources :countdowns
  resources :devise
  resources :registrations
  resources :checkout
  resources :sell_shoes
  resources :buy_shoes

  resources :posts

   devise_for :users

  root :to => 'posts#index'

end

app/models/shoe.rb
class Shoe < ActiveRecord::Base
  has_attached_file :image,
                    :styles => { :medium => "300x300>",
                                  :thumb => "100x100>" }
  
  def price
    price_in_cents.to_f / 100
  end
  
  def price= new_price
    self.price_in_cents = (new_price.to_f * 100)
  end
  
  validates :name, :brand, :exclusion => {:in => ["adidas", "puma","reebok","kswiss", "k-swiss", ], :message => "This shoe is not exotic!, sorry" }
  
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  # GET /shoes
  # GET /shoes.json
  
  def create
    @shoe = shoe.create(params[:shoe])
    end
  end
  
  def index
    @shoes = Shoe.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @shoes }
    end
  end

  # GET /shoes/1
  # GET /shoes/1.json
  def show
    @shoe = Shoe.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @shoe }
    end

  # GET /shoes/new
  # GET /shoes/new.json
  def new
    @shoe = Shoe.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @shoe }
    end
  end

  # GET /shoes/1/edit
  def edit
    @shoe = Shoe.find(params[:id])
  end

  # POST /shoes
  # POST /shoes.json
  def create
    @shoe = Shoe.new(params[:shoe])

    respond_to do |format|
      if @shoe.save
        format.html { redirect_to @shoe, notice: 'Shoe was successfully created.' }
        format.json { render json: @shoe, status: :created, location: @shoe }
      else
        format.html { render action: "new" }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /shoes/1
  # PUT /shoes/1.json
  def update
    @shoe = Shoe.find(params[:id])

    respond_to do |format|
      if @shoe.update_attributes(params[:shoe])
        format.html { redirect_to @shoe, notice: 'Shoe was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @shoe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shoes/1
  # DELETE /shoes/1.json
  def destroy
    @shoe = Shoe.find(params[:id])
    @shoe.destroy

    respond_to do |format|
      format.html { redirect_to shoes_url }
      format.json { head :ok }
    end
  end
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/views/shoes/_form.html.haml
= form_for @shoe do |f|
  -if @shoe.errors.any?
    #error_explanation
      %h2= "#{pluralize(@shoe.errors.count, "error")} prohibited this shoe from being saved:"
      %ul
        - @shoe.errors.full_messages.each do |msg|
          %li= msg
          
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :brand
    = f.text_field :brand
  .field
    = f.label :size
    = f.text_field :size
  .field
    = f.label :price
    = f.text_field :price
  .field
    = f.label :condition
    = f.text_field :condition
  .field
    = f.label :description
    = f.text_field :description
    
= form_for(@shoe,:html => {:multipart => true}) do |f|
  %div{:class => "field"}
    = f.file_field :shoe, images
    

  .actions
  
    %div
    = f.submit 'submit'

app/views/shoes/edit.html.haml
%h1 Editing shoe

= render 'form'

= link_to 'Show', @shoe
\|
= link_to 'Back', shoes_path

%form_for :shoe, :html => {:multipart => true} do |form|
    form.file_field :shoe images

app/views/shoes/index.html.haml
%h1 Exotic Kicks For Sale

%table
  %tr
    %th
    %th
    %th

  - @shoes.each do |shoe|
    %tr
      %td= link_to 'Show', shoe
      %td= link_to 'Edit', edit_shoe_path(shoe)
      %td= link_to 'Delete Shoe', shoe, :confirm => 'Are you sure?', :method => :delete

%br

= link_to 'Want To Sell Your Exoctic Kicks?', new_shoe_path

app/views/shoes/new.html.haml
%h1 Sell Your Exoctics!
%h2 Please fill out all information below

//%form_for :shoe, :html => {:multipart => true} do |form|
//%form.file_field :shoe_images


// render :partial => 'form', :locals => {:shoe => @shoe}

= render 'form'
= link_to 'Back', shoes_path

app/views/shoes/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_shoe_path(@shoe)
\|
= link_to 'Back', shoes_path

= image_tag @shoe.shoe images.url
= image_tag @shoe.shoe images.url(:medium)
= image_tag @shoe.shoe images.url(:thumb)